### ISSUE TITLE
Add php-ts to PHP support from external packages

### ISSUE THREAD

**Issue by zonuexe** [emacs-php/php-ts-mode#55]
While not blocking the release of php-ts-mode even if these supports are not merged, it would be ideal if they were available out-of-box for those who will try them when php-ts-mode is released, migrating from PHP Mode.

- [x] all-the-icons https://github.com/domtronn/all-the-icons.el/pull/382
- [x] cape https://github.com/minad/cape/pull/107
- [x] codeium.el https://github.com/Exafunction/codeium.el/pull/91
- [x] Company https://github.com/company-mode/company-mode/pull/1450
- [x] company-php https://github.com/xcwen/ac-php/pull/156
- [x] EditorConfig https://github.com/editorconfig/editorconfig-emacs/pull/318
- [x] Eglot https://debbugs.gnu.org/cgi/bugreport.cgi?bug=68870
- [x] Flycheck https://github.com/flycheck/flycheck/pull/2050
- [x] LSP Mode https://github.com/emacs-lsp/lsp-mode/pull/4318
- [x] lsp-bridge https://github.com/manateelazycat/lsp-bridge/pull/843
- [x] quickrun https://github.com/emacsorphanage/quickrun/pull/149
- [x] yasnippet-snippets https://github.com/AndreaCrotti/yasnippet-snippets/pull/481
- [X] nerd-icons https://github.com/rainstormstudio/nerd-icons.el/pull/82

**Comment by piotrkwiecinski** [comment]
Eglot would require changes as well https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/eglot.el#L245-L249 . I believe it'll require sending patch to the emacs core.

It's a 1 line. I haven't pushed any patches to the core. I'll give it a go at the end of the week.

**Comment by zonuexe** [comment]
I've sent PRs to most of the packages hosted on GitHub that are currently in active development. If you find any Lisp packages that are not supported, please feel free to comment.

**Comment by piokwiecinski-tm** [comment]
@zonuexe eglot updated https://debbugs.gnu.org/cgi/bugreport.cgi?bug=68870

**Comment by piotrkwiecinski** [comment]
@zonuexe eglot updated and submitted https://debbugs.gnu.org/cgi/bugreport.cgi?bug=68870

**Comment by zonuexe** [comment]
@piotrkwiecinski 
Thanks! That commit has already been [merged](https://emba.gnu.org/emacs/emacs/-/commit/5f56bc1cdfcd474dd9cfad07240df6c252abd35c), so it should be reflected in the next Emacs 29 release and [elgot](https://elpa.gnu.org/packages/eglot.html) package.

**Comment by piotrkwiecinski** [comment]
- [x] nerd-icons https://github.com/rainstormstudio/nerd-icons.el/pull/82

**Comment by piotrkwiecinski** [comment]
I'm going to close this ticket. If we need to track other integrations these can be tracked in separate tickets.
