### ISSUE TITLE
Error loading autoloads: (void-variable treesit-language-source-alist)

### ISSUE THREAD

**Issue by piotrkwiecinski** [emacs-php/php-ts-mode#58]
It's present in CI and  when I run tests on local.

I think it's caused by:
```
;;;###autoload
(add-to-list 'treesit-language-source-alist
             '(php "https://github.com/tree-sitter/tree-sitter-php" "master" "php/src"))
```

https://github.com/emacs-php/php-ts-mode/blob/master/php-ts-mode.el#L356-L359

**Comment by zonuexe** [comment]
@piotrkwiecinski
Thank you for your reporting. If the problem is not fixed, please reopen this issue.
